models:
- api_key: env:OPENAI_API_KEY
  max_tokens: 1500
  model_name: gpt-4-turbo-2024-04-09
  name: gpt4-turbo
  temperature: 0.7
  type: openai
- api_key: env:OPENAI_API_KEY
  max_tokens: 2000
  model_name: gpt-4o
  name: gpt4o
  temperature: 0.5
  type: openai
- api_key: env:ANTHROPIC_API_KEY
  max_tokens: 2000
  model_name: claude-3-opus-20240229
  name: claude-opus
  temperature: 0.7
  type: anthropic
- api_key: env:ANTHROPIC_API_KEY
  max_tokens: 1500
  model_name: claude-3-sonnet-20240229
  name: claude-sonnet
  temperature: 0.7
  type: anthropic
- api_key: env:GOOGLE_API_KEY
  model_name: gemini-1.5-pro-latest
  name: gemini-pro
  temperature: 0.7
  type: gemini
- api_key: env:MISTRAL_API_KEY
  max_tokens: 1000
  model_name: mistral-large-latest
  name: mistral-large
  safe_prompt: true
  temperature: 0.7
  type: mistral
- api_key: env:DEEPSEEK_API_KEY
  max_tokens: 1000
  model_name: deepseek-chat
  name: deepseek-v2
  temperature: 0.3
  type: deepseek
- api_key: env:PHI4_API_KEY
  model_name: phi-4
  name: phi4-base
  type: phi4
- model_name: llama3:70b
  name: llama3-70b
  num_ctx: 4096
  temperature: 0.7
  type: ollama
- model_name: llama3:8b
  name: llama3-8b
  num_ctx: 4096
  temperature: 0.7
  type: ollama
- model_name: mixtral:8x22b
  name: mixtral-8x22b
  num_ctx: 32768
  temperature: 0.8
  type: ollama
- name: dummy-model
  type: dummy
- model_name: llama3.1:8b
  name: llama3-custom
  num_ctx: 8192
  temperature: 0.8
  type: ollama
